/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/medias/Building L.glb -o app/Propuesta1/components/Building.jsx -k -K -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Building(props) {
  const { nodes, materials } = useGLTF("/medias/Building L.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <mesh
            name="Building_L"
            geometry={nodes.Building_L.geometry}
            material={materials.Atlas}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/medias/Building L.glb");
