/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/medias/HarneroGLTFDRACO.glb -o app/Propuesta1/components/Harnero.jsx -k -K -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Harnero(props) {
  const { nodes, materials } = useGLTF("/medias/HarneroGLTFDRACO.glb");
  return (
    <group {...props} dispose={null}>
      <group name="AuxScene">
        <mesh
          name="_01_03_DI_299"
          geometry={nodes._01_03_DI_299.geometry}
          material={materials.mat_0}
          position={[-2.321, 2.122, -1.124]}
          rotation={[0.397, -0.618, 0.108]}
        />
        <instancedMesh
          args={[nodes.mesh_0.geometry, materials.mat_0, 154]}
          name="mesh_0"
          instanceMatrix={nodes.mesh_0.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_1.geometry, materials.mat_0, 121]}
          name="mesh_1"
          instanceMatrix={nodes.mesh_1.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_2.geometry, materials.mat_0, 11]}
          name="mesh_2"
          instanceMatrix={nodes.mesh_2.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_3.geometry, materials.mat_0, 10]}
          name="mesh_3"
          instanceMatrix={nodes.mesh_3.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_4.geometry, materials.mat_0, 2]}
          name="mesh_4"
          instanceMatrix={nodes.mesh_4.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_6.geometry, materials.mat_0, 234]}
          name="mesh_6"
          instanceMatrix={nodes.mesh_6.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_7.geometry, materials.mat_0, 36]}
          name="mesh_7"
          instanceMatrix={nodes.mesh_7.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_8.geometry, materials.mat_0, 6]}
          name="mesh_8"
          instanceMatrix={nodes.mesh_8.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_9.geometry, materials.mat_0, 6]}
          name="mesh_9"
          instanceMatrix={nodes.mesh_9.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_10.geometry, materials.mat_0, 6]}
          name="mesh_10"
          instanceMatrix={nodes.mesh_10.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_11.geometry, materials.mat_0, 6]}
          name="mesh_11"
          instanceMatrix={nodes.mesh_11.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_12.geometry, materials.mat_0, 6]}
          name="mesh_12"
          instanceMatrix={nodes.mesh_12.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_13.geometry, materials.mat_0, 10]}
          name="mesh_13"
          instanceMatrix={nodes.mesh_13.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_14.geometry, materials.mat_0, 2]}
          name="mesh_14"
          instanceMatrix={nodes.mesh_14.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_15.geometry, materials.mat_0, 2]}
          name="mesh_15"
          instanceMatrix={nodes.mesh_15.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_16.geometry, materials.mat_0, 2]}
          name="mesh_16"
          instanceMatrix={nodes.mesh_16.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_17.geometry, materials.mat_0, 4]}
          name="mesh_17"
          instanceMatrix={nodes.mesh_17.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_18.geometry, materials.mat_0, 4]}
          name="mesh_18"
          instanceMatrix={nodes.mesh_18.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_19.geometry, materials.mat_0, 4]}
          name="mesh_19"
          instanceMatrix={nodes.mesh_19.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_20.geometry, materials.mat_0, 8]}
          name="mesh_20"
          instanceMatrix={nodes.mesh_20.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_21.geometry, materials.mat_0, 4]}
          name="mesh_21"
          instanceMatrix={nodes.mesh_21.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_22.geometry, materials.mat_0, 8]}
          name="mesh_22"
          instanceMatrix={nodes.mesh_22.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_23.geometry, materials.mat_0, 16]}
          name="mesh_23"
          instanceMatrix={nodes.mesh_23.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_24.geometry, materials.mat_0, 8]}
          name="mesh_24"
          instanceMatrix={nodes.mesh_24.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_25.geometry, materials.mat_0, 24]}
          name="mesh_25"
          instanceMatrix={nodes.mesh_25.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_26.geometry, materials.mat_0, 8]}
          name="mesh_26"
          instanceMatrix={nodes.mesh_26.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_27.geometry, materials.mat_0, 2]}
          name="mesh_27"
          instanceMatrix={nodes.mesh_27.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_28.geometry, materials.mat_0, 2]}
          name="mesh_28"
          instanceMatrix={nodes.mesh_28.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_29.geometry, materials.mat_0, 2]}
          name="mesh_29"
          instanceMatrix={nodes.mesh_29.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_30.geometry, materials.mat_0, 2]}
          name="mesh_30"
          instanceMatrix={nodes.mesh_30.instanceMatrix}
        />
        <instancedMesh
          args={[nodes.mesh_31.geometry, materials.mat_0, 2]}
          name="mesh_31"
          instanceMatrix={nodes.mesh_31.instanceMatrix}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/medias/HarneroGLTFDRACO.glb");
