/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/medias/HarneroCollada.glb -o app/Propuesta1/components/HarneroCollada.jsx -k -K -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HarneroCollada(props) {
  const { nodes, materials } = useGLTF("/medias/HarneroCollada.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="node0"
          geometry={nodes.node0.geometry}
          material={materials._01_03_DI_01_T2}
          rotation={[0.795, 0.006, -1.116]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/medias/HarneroCollada.glb");
