/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/medias/LOGO3D.glb -o app/Propuesta1/components/LOGO3D.jsx -k -K -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function LOGO3D(props) {
  const { nodes, materials } = useGLTF("/medias/LOGO3D.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Text"
          geometry={nodes.Text.geometry}
          material={nodes.Text.material}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/medias/LOGO3D.glb");
