/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/medias/HarneroOptimizado.glb -o app/Propuesta1/components/HarneroOptimizado.jsx -k -K -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function HarneroOptimizado(props) {
  const { nodes, materials } = useGLTF("/medias/HarneroOptimizado.glb");
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="node0"
          geometry={nodes.node0.geometry}
          material={materials._01_03_DI_01_T2}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/medias/HarneroOptimizado.glb");
